language: python
python:
  - "2.7"
  - "3.4"
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest2.__main__ discover; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python -m unittest discover; fi